import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth/options"
import { isGoogleConfigured } from "@/lib/google/auth"
import { getTopKeywords } from "@/lib/google/search-console"
import { listPosts } from "@/lib/wordpress/client"
import { query } from "@/lib/db/connection"

export async function GET(req: Request) {
  const session = await getServerSession(authOptions)
  if (!session) {
    return Response.json({ error: "Non autorise" }, { status: 401 })
  }

  const { searchParams } = new URL(req.url)
  const type = searchParams.get("type") ?? "keywords"

  try {
    // Race each external call against a 8s timeout to prevent hanging
    const withTimeout = <T,>(promise: Promise<T>, fallback: T): Promise<T> =>
      Promise.race([promise, new Promise<T>((resolve) => setTimeout(() => resolve(fallback), 8_000))])

    // Get latest SEO report from DB (generated by seo-report cron)
    let latestReport: { data_json: string; summary: string; created_at: string } | null = null
    try {
      const rows = await withTimeout(
        query<{ data_json: string; summary: string; created_at: string }>(
          "SELECT data_json, summary, created_at FROM wp_lou_seo_reports WHERE report_type = 'weekly' ORDER BY created_at DESC LIMIT 1",
        ),
        [],
      )
      latestReport = rows[0] ?? null
    } catch {
      // DB may not be available
    }

    // Get real keywords from Search Console if configured
    let keywords: { keyword: string; position: number; trend: "up" | "down" | "stable"; clicks: number; impressions: number }[] = []
    let searchConsoleConnected = false

    if (isGoogleConfigured()) {
      try {
        keywords = await withTimeout(getTopKeywords(15), [])
        searchConsoleConnected = keywords.length > 0
      } catch {
        // Search Console may fail
      }
    }

    // Get article stats from WordPress
    let totalArticles = 0
    try {
      const posts = await withTimeout(listPosts({ per_page: 100, status: "publish" }), [])
      totalArticles = posts.length
    } catch {
      // WP may be down
    }

    // Parse report data
    let reportData: Record<string, unknown> = {}
    if (latestReport) {
      try {
        reportData = JSON.parse(latestReport.data_json)
      } catch {
        // ignore
      }
    }

    const score = (reportData.score as number) ?? null
    const recommendations = (reportData.recommendations as string[]) ?? []
    const strengths = (reportData.strengths as string[]) ?? []
    const weaknesses = (reportData.weaknesses as string[]) ?? []
    const articleIdeas = (reportData.article_ideas as unknown[]) ?? []

    // Build response based on requested type
    switch (type) {
      case "keywords":
        return Response.json({
          searchConsoleConnected,
          keywords: keywords.map((k) => ({
            keyword: k.keyword,
            position: k.position,
            trend: k.trend,
            volume: k.impressions, // Use impressions as proxy for volume
          })),
        })

      case "audit":
        return Response.json({
          searchConsoleConnected,
          score,
          totalArticles,
          strengths,
          weaknesses,
          issues: weaknesses.map((w, i) => ({
            severity: i < 2 ? "error" : "warning",
            message: w,
          })),
          reportDate: latestReport?.created_at ?? null,
        })

      case "recommendations":
        return Response.json({
          recommendations,
          articleIdeas,
          reportDate: latestReport?.created_at ?? null,
        })

      default:
        return Response.json({ error: "Type invalide" }, { status: 400 })
    }
  } catch (err) {
    return Response.json(
      { error: err instanceof Error ? err.message : "Erreur audit SEO" },
      { status: 500 },
    )
  }
}
